#!/bin/bash

g++ -g -fPIC -std=c++17 -c ThreadSafeCache.cpp
g++ -g -fPIC -std=c++17 -c ObservableCache.cpp
g++ -g -std=c++17 ThreadSafeCache.o ObservableCache.o -fPIC -shared -o libObservableCache.so -lpthread
#g++ -g -std=c++17 ThreadSafeCache.o ObservableCache.o MainTest2.cpp -o MainTest2.out -lpthread
